demo_project/urls.py
from django.contrib import admin
from django.urls import path
from demo_app import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'demo_app'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login, name='login'),
    path('dashboard/', views.dasboard_view, name='dash'),
    path('worksite/', views.WorksiteView.as_view(), name='work'),
    path('Information/', views.Information, name='Inform'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

demo_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms


# Create your models here.
class Worksite(models.Model):
    """ Add New Worksite Form """
    name = models.CharField(max_length=150)
    shift = models.CharField(max_length=255)
    buffer_time = models.TimeField()
    cutoff_time = models.TimeField()
    contact_no = models.CharField(max_length=12)
    address = models.TextField()
    device = models.CharField(max_length=255)

    class meta:
        model = 'Worksite'
        fields = '__all__'

demo_app/forms.py
from django import forms


class EditWorksiteForm(forms.Form):
    """ Add New Worksite Form """
    name = forms.CharField(max_length=150, label='Name')
    shift = forms.ChoiceField(choices=[(x, x) for x in range(1, 13)], label='Shift Timing (AM/ PM)')
    buffer_time = forms.TimeField(widget=forms.TimeInput(
        format='%M'), label='Start Buffer time for reports (Minutes)', input_formats=['%M', ])
    cutoff_time = forms.TimeField(widget=forms.TimeInput(format='%M'),
                                  label='Patrol start cut-off time (Minutes)', input_formats=['%M', ])
    contact_no = forms.CharField(max_length=12, label='Contact Number (+65)')
    address = forms.CharField(widget=forms.Textarea)
    device = forms.CharField(max_length=255, label='Device IMEI / IMEI1 Number')

    def __init__(self, *args, **kwargs):
        super(EditWorksiteForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        # field.widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['class'] = 'form-control   '

demo_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.contrib import messages
from django.contrib.auth import login as auth_login
from .models import Worksite
from .forms import EditWorksiteForm
from django.views import View
from django.contrib.auth.decorators import login_required


@login_required(login_url='/login/')
def Information(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            object = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            object.set_password(password)
            object.save()
            profile = Employee()
            profile.user = object
            profile.save()
            messages.success(
                request, 'Your account has been created! You are now able to login')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'register.html', {'form': form})


def login(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user:
            if user.is_active and user.is_superuser:
                auth_login(request, user)
                if request.GET.get('next', None):
                    return redirect(request.GET.get['next'])
                return redirect('dash')
            else:
                if user.is_active:
                    auth_login(request, user)
                return redirect('work')
        else:
            return redirect('login')
    else:
        return render(request, 'login.html', {})


def dasboard_view(request):
    return render(request, 'dashboard.html', {'range': range(10)})


class WorksiteView(View):

    def get(self, request, *args, **kwargs):
        form = EditWorksiteForm()
        return render(request, 'add-worksite.html', {'form': form})

templates/add-worksite.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}

<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <div class="col-md-3 left_col menu_fixed">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="#" class="site_title"><img src="{% static 'images/logo-small.png' %}" alt=""></a>
          </div>
          <div class="profile clearfix">
            <div class="profile_info">
              <a href="#" class="profile-logo"><img src="{% static 'images/CBM-logo-side.png' %}" alt=""></a>
              <div class="profile-name">
                <h2>CBM Pte Ltd</h2>
                <p>cbm@gmail.com</p>
              </div>
            </div>
          </div>
          <!-- /menu profile quick info -->
          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <ul class="nav side-menu">
                <li><a>Dashboard</a> </li>
                <li><a>Add Worksite </a></li>
                <li><a>Route Listing </a></li>
                <li><a>User Management <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="#">Link 1</a></li>
                    <li><a href="#">Link 2</a></li>
                    <li><a href="#">Link 3</a></li>
                  </ul>
                </li>
                <li><a>Reporting <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="#">Incident Reports</a></li>
                    <li><a href="#">Patrol Reports</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
          <!-- /sidebar menu -->
        </div>
      </div>
      <!-- page content -->
      <div class="right_col" role="main">
        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>
              <div class="page-title">
                <div class="row">
                  <div class="col-md-6">
                    <h2>Add Worksite </h2>
                    <a class="brad" href="#">Dashboard</a> <span>/ Add Worksite </span>
                  </div>
                  <div class="col-md-6 search-action">
                    <a href="#" class="btn btn-primary">Export Report</a>
                  </div>
                </div>
              </div>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->
        <div class="wrapper">
          <div class="details">
            <div class="info-bg">
              <form action="" method="POST" novalidate>
                {% csrf_token %}
                {% for field in form %}
                {% if forloop.counter == 1 %}
                <div class="row">
                  {% endif %}
                  {% if forloop.counter == 1 or forloop.counter == 2 or forloop.counter == 3 %}
                  <div class="col-md-4">
                    <div class="form-group">
                      <label>{{ field.label }}</label>
                      {{ field }}
                    </div>
                    <span class="text-danger">{{ field.errors }}</span>
                  </div>
                  {% endif %}
                  {% if forloop.counter == 4 %}
                </div>
                <div class="row">
                  <div class="col-md-8">
                    <div class="row">
                      {% endif %}
                      {% if forloop.counter == 4 or forloop.counter == 5 %}
                      <div class="col-md-6">
                        <div class="form-group">
                          <label>{{ field.label }}</label>
                          {{ field }}
                        </div>
                        <span class="text-danger">{{ field.errors }}</span>
                      </div>
                      {% endif %}
                      {% if forloop.counter == 6 %}
                      <div class="col-md-12">
                        <div class="form-group">
                          <label>{{ field.label }} </label>
                          {{ field }}
                        </div>
                        <span class="text-danger">{{ field.errors }}</span>
                      </div>
                    </div>
                  </div>
                  {% endif %}
                  {% if forloop.counter == 7 %}
                  <div class="col-md-4">
                    <div class="form-group" id="fullGang">
                      <label>{{ field.label }}</label>
                      <div class="row">
                        <div class="col-md-8">
                          {{ field }}
                          <span class="text-danger">{{ field.errors }}</span>
                        </div>
                        <div class="col-md-4">
                          <button type="button" id="add-device" name="button" class="btn btn-plus"><i class="fa fa-plus"></i></button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                {% endif %}
                {% endfor %}
                <div class="row">
                  <div class="col-md-12 text-right">
                    <button type="button" class='btn btn-cancle'>Cancel</button>
                    <input type="submit" class="btn btn-primary" value="Save">
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /page content -->
    {% endblock %}
    {% block script %}
    <script type="text/javascript">
      // Remove device Function
      function removeDevice(elem) {
        var device_counter = localStorage.getItem('device_counter');
        $(elem).parent().parent().parent().remove();
        device_counter -= 1;
        localStorage.setItem('device_counter', device_counter);
      }
      $(document).ready(function() {

        $('#id_name').datetimepicker({
           format: 'hh:mm',
           // timeFormat: 'hh:mm tt',
           minView: 4,
           maxView: 3,
           autoclose: true
        });
        // Add Device
        var device_counter = 1;
        localStorage.setItem('device_counter', device_counter);
        $('#add-device').click(function() {
          var device_counter = localStorage.getItem('device_counter');
          if (device_counter <= 9) {
            html = "<div class='form-group'>\
              <label>Device IMEI / IMEI1 Number</label>\
              <div class='row'>\
                <div class='col-md-8'>\
                  <input type='text' name='device' maxlength='15' class='form-control' required id='id_device'>\
                </div>\
                <div class='col-md-4'>\
                  <button onclick='removeDevice(this)' type='button' id='rem-device-" + device_counter + "' name='button' class='btn btn-minus'><i class='fa fa-times'></i></button>\
                </div>\
              </div>\
            </div>"

            $('#fullGang').after(html);
            device_counter = parseInt(device_counter) + 1;
            localStorage.setItem('device_counter', device_counter);
          } else {
            alert('Sorry! You can add upto 10 devices only.');
          }
        });
      });
    </script>
    {% endblock %}

templates/base.html
{% load staticfiles %}
{% load static %}

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="images/favicon.ico" type="image/ico" />
    <title>Infornest</title>

    <link href='{% static "vendors/bootstrap/dist/css/bootstrap.min.css" %}' rel="stylesheet">
    <link href='{% static "css/bootstrap-datetimepicker.min.css" %}' rel="stylesheet" media="screen">
    <link href='{% static "vendors/font-awesome/css/font-awesome.min.css" %}' rel="stylesheet">
    <link href='{% static "vendors/iCheck/skins/flat/green.css" %}' rel="stylesheet">
    <link href='{% static "vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" %}' rel="stylesheet" />
    <link href='{% static "vendors/bootstrap-daterangepicker/daterangepicker.css" %}' rel="stylesheet">
    <link href='{% static "vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" %}' rel="stylesheet">
    <link href='{% static "vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" %}' rel="stylesheet">
    <link href='{% static "vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" %}' rel="stylesheet">
    <link href='{% static "vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" %}' rel="stylesheet">
    <link href='{% static "vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" %}' rel="stylesheet">
    <link href='{% static "vendors/select2/dist/css/select2.min.css" %}' rel="stylesheet">
    <link href='{% static "vendors/bootstrap-daterangepicker/daterangepicker.css" %}' rel="stylesheet">
    <link href='{% static "vendors/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css" %}' rel="stylesheet">
    <link href='{% static "css/owl.carousel.min.css" %}' rel="stylesheet">
    <link href='{% static "css/owl.theme.default.min.css" %}' rel="stylesheet">
    <link href='{% static "css/custom.css" %}' rel="stylesheet">
  </head>

  {% block body_block %}{% endblock %}

    <script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.js' %}" charset="UTF-8"></script>
    <script type="text/javascript" src="{% static 'js/locales/bootstrap-datetimepicker.fr.js' %}" charset="UTF-8"></script>
    <script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>
    <script src="{% static 'vendors/DateJS/build/date.js' %}"></script>
    <script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
    <script src="{% static 'vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
    <script src="{% static 'vendors/jszip/dist/jszip.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/custom.min.js' %}"></script>
    {% block script %}{% endblock %}

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}


    <!-- jQuery custom content scroller -->

    <!-- bootstrap-daterangepicker -->

    <!-- iCheck -->
    <!-- jQuery custom content scroller -->
    <!-- bootstrap-daterangepicker -->
    <!-- Datatables -->
    <!-- bootstrap-daterangepicker -->



<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <div class="col-md-3 left_col menu_fixed">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="#" class="site_title"><img src="{% static 'images/logo-small.png' %}" alt=""></a>
          </div>
          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <div class="profile_info">
              <a href="#" class="profile-logo"><img src="{% static 'images/CBM-logo-side.png' %}" alt=""></a>
              <div class="profile-name">
                <h2>CBM Pte Ltd</h2>
                <p>cbm@gmail.com</p>
              </div>
            </div>
          </div>
          <!-- /menu profile quick info -->
          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <ul class="nav side-menu">
                <li><a>Dashboard</a> </li>
                <li><a href="{% url 'work' %}">Add Worksite </a></li>
                <li><a>Route Listing </a></li>
                <li><a>User Management <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="{% url 'dash' %}">Link 1</a></li>
                    <li><a href="#">Link 2</a></li>
                    <li><a href="#">Link 3</a></li>
                  </ul>
                </li>
                <li><a>Reporting <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="#">Incident Reports</a></li>
                    <li><a href="#">Patrol Reports</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
          <!-- /sidebar menu -->
        </div>
      </div>
      <!-- page content -->
      <div class="right_col" role="main">
        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>
              <div class="page-title">
                <div class="row">
                  <div class="col-md-6">
                    <h2>Dashboard</h2>
                  </div>
                  <div class="col-md-6 search-action">
                    <img src="{% static 'images/CBM_logo-top.png' %}">
                  </div>
                </div>
              </div>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->
        <div class="wrapper">
          <div class="dashboard">
            <div class="row">
              <div class="col-md-3 dash-datetime">
                <label>Date <i class="fa fa-calendar"></i></label>
                <p>29-Apr-2019</p>
              </div>
              <div class="col-md-3 dash-datetime">
                <label>Day <i class="fa fa-sun-o"></i></label>
                <p>Wednesday</p>
              </div>
              <div class="col-md-3 dash-datetime">
                <label>Time <i class="fa fa-clock-o"></i></label>
                <p>07:30 PM</p>
              </div>
            </div>
            <div class="row" id="dragAnwr">
              {% for x in range %}
              <div class="col-md-3"  draggable="true">
                <div class="dash-data green">
                  <span>1/4<br><small>Attendance</small></span>
                  <h2>CBM</h2>
                  <div class="details-dash">
                    <div class="row">
                      <div class="col-md-6">Incidents</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">Irregular Patrols</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">Monthly
                        Supervisory Check</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
              <!-- <div class="col-md-3">
                <div class="dash-data red">
                  <span>1/4<br><small>Attendance</small></span>
                  <h2>Certis</h2>
                  <div class="details-dash">
                    <div class="row">
                      <div class="col-md-6">Incidents</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">Irregular Patrols</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">Monthly
                        Supervisory Check</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                  </div>
                </div>
              </div> -->
              <!-- <div class="col-md-3">
                <div class="dash-data green">
                  <span>1/4<br><small>Attendance</small></span>
                  <h2>Gilb Ltd</h2>
                  <div class="details-dash">
                    <div class="row">
                      <div class="col-md-6">Incidents</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">Irregular Patrols</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">Monthly
                        Supervisory Check</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                  </div>
                </div>
              </div> -->
              <!-- <div class="col-md-3">
                <div class="dash-data purple">
                  <span>1/4<br><small>Attendance</small></span>
                  <h2>Lou Pte Ltd</h2>
                  <div class="details-dash">
                    <div class="row">
                      <div class="col-md-6">Incidents</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">Irregular Patrols</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">Monthly
                        Supervisory Check</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                  </div>
                </div>
              </div> -->
              <!-- <div class="col-md-3">
                <div class="dash-data green">
                  <span>1/4<br><small>Attendance</small></span>
                  <h2>MyGPS</h2>
                  <div class="details-dash">
                    <div class="row">
                      <div class="col-md-6">Incidents</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">Irregular Patrols</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">Monthly
                        Supervisory Check</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                  </div>
                </div>
              </div> -->
              <!-- <div class="col-md-3">
                <div class="dash-data purple">
                  <span>1/4<br><small>Attendance</small></span>
                  <h2>MyGPS</h2>
                  <div class="details-dash">
                    <div class="row">
                      <div class="col-md-6">Incidents</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">Irregular Patrols</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">Monthly
                        Supervisory Check</div>
                      <div class="col-md-6 text-right"><strong>8</strong></div>
                    </div>
                  </div>
                </div>
              </div> -->
            </div>
          </div>
        </div>
      </div>
      <!-- /page content -->
    </div>
  </div>
  {% endblock %}
  {% block script %}
    <script src='{% static "vendors/datatables.net-bs/js/dataTables.bootstrap.min.js" %}'></script>
    <script src="{% static 'js/custom.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <!-- < script >
  $(document).ready(function() {
    $('#myTable').DataTable();
  });
</script> -->
<script type="text/javascript">
  // $( function() {
  //   $( "#dragAnwr" ).draggable();
  // } );
  // $( "#dragAnwr" ).draggable();

  // $( ".dropbox" ).droppable({
    // drop: function( event, ui ) {
      // remove flag class
      // $(this).siblings().removeClass('selected');
      // add class to the dropped element
      // $(this).addClass('selected');
    // },
    // hoverClass: "drop-hover"
  // });
  $("#dragAnwr").sortable({

  // axis: "y",
  // axis:"x",
  revert: true,
  // scroll: true,
  // placeholder: "sortable-placeholder",
  cursor: "move"

});
</script>

</body>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block body_block %}
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Infornest</title>
  <!-- Bootstrap -->
  <!-- NProgress -->
  <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
  <!-- Animate.css -->
  <link href="{% static 'vendors/animate.css/animate.min.css' %}" rel="stylesheet">
  <!-- Custom Theme Style -->
</head>

<body class="login">
  <div>
    <div class="login_wrapper">
      <div class="logo">
        <a href="#">
          <img src="{% static "images/login-logo.png" %}" alt="">
        </a>
      </div>
      <div class="animate form login_form">
        <section class="login_content">
          <form method="post">
            {% csrf_token %}
            <h1>Login</h1>
            <div class="form-group">
              <label>Email</label>
              <input type="text" placeholder="username" name="username" required>
            </div>
            <div class="password-block form-group">
              <label>Password</label>
              <input type="password" placeholder="Password" name="password" required="" />
              <i toggle="#password-field" class="fa fa-fw toggle-password fa-eye" aria-hidden="true"></i>
            </div>
            <div>
              <a>
                <button type="submit" class="btn btn-default submit">Login</button>
              </a>
            </div>
            <div class="clearfix"></div>
            <p class="change_link">
              <a href="#signup" class="to_register">Forgot password? </a>
            </p>
          </form>
        </section>
      </div>
    </div>
  </div>
    <!-- Custom Theme Scripts -->
    < script src = "{% static 'js/custom.min.js' %}" > < /script>


    <script>
      $(document).ready(function() {
        $(".toggle-password").click(function() {

          $(this).toggleClass("fa-eye fa-eye-slash");
          var input = $($(this).attr("toggle"));
          if (input.attr("type") == "password") {
            input.attr("type", "text");
          } else {
            input.attr("type", "password");
          }
        });
      });
      </script>


</body>
{% endblock %}

templates/register.html
{% load widget_tweaks %}

<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <style>
    ul {
      list-style: none;
    }

    input[type=radio],
    input.radio {
      margin: 2px 0 0 2px;
    }
  </style>

</head>

<form method="POST" class="post-form" enctype="multipart/form-data" novalidate>
  {% csrf_token %}
  <div class="container">
    <div class="form-group row">
      <label class="col-sm-1 col-form-label"></label>
      <div class="col-sm-4">
        <h3>Enter Details</h3>
      </div>
    </div>

    {% for field in form %}
    <div class="form-group row">
      <label class="col-sm-2 col-form-label">{{ field.label_tag }}</label>
      <div class="col-sm-4">
        {% if form.is_bound %}
        {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
        <div class="invalid-feedback">
          {{ error }}
        </div>
        {% endfor %}
        {% else %}
        {% render_field field class="form-control is-valid" %}
        {% endif %}
        {% else %}
        {% render_field field class="form-control" %}
        {% endif %}
      </div>
    </div>
    {% endfor %}

    <div class="form-group row">
      <label class="col-sm-1 col-form-label"></label>
      <div class="col-sm-4">
        <button type="submit" class="btn btn-primary">Submit</button>
        <a href="{% url 'login' %}" class="btn btn-info">Existing User!!! Login</a>
      </div>
    </div>
  </div>
</form>